[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd client && npm ci", "cd server && npm ci"]

[phases.build]
cmds = ["cd client && npm run build", "cd server && npm run build"]

[start]
cmd = "cd server && npm run migrate && npm start"
